<a href="https://colab.research.google.com/github/Santhoshkumar5655/datasciencelearning/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
df =pd.read_excel("/content/drive/MyDrive/datsetsfordatasciencebytexl/student_dataset_20rows.xlsx")

In [ ]:
print(df)

In [12]:
# axis = 0 => removing rows
# axis = 1 => removing columns
df.drop("City", axis =1, inplace =True)

In [ ]:
df

In [16]:
df.drop(0, axis=0, inplace=True)

In [ ]:
df

In [ ]:
import pandas as pd
df =pd.read_excel("/content/drive/MyDrive/datsetsfordatasciencebytexl/student_dataset_20rows.xlsx")
print(df)

In [23]:
#selecting columns
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [38]:
df["Marks"]

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [39]:
df["Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [40]:
df["City"]

0      Vijayawada
1       Hyderabad
2         Chennai
3       Bangalore
4          Mumbai
5           Delhi
6            Pune
7         Kolkata
8           Vizag
9        Tirupati
10       Warangal
11         Guntur
12        Nellore
13         Kadapa
14        Kurnool
15         Ongole
16    Rajahmundry
17          Eluru
18        Khammam
19      Nizamabad
Name: City, dtype: object

In [ ]:
df[["Name", "Age"]]

In [ ]:
df[["Name", "Age","City"]]

In [ ]:
df

In [ ]:
#selecting rows using iloc function
# iloc = integer location
df.iloc[0]

In [ ]:
df.iloc[0:3]

In [ ]:
# selecting specific rows and columns
# df.iloc[rowselection, columnselection]
df.iloc[0:3, 0:3]

In [ ]:
df.iloc[0,0:3]

In [ ]:
df.iloc[[0,1,2,3]]

In [ ]:
df.loc[0:2]

In [ ]:
# suppose if i am accesing multiple rows
# in iloc function suppose my range is 0 to n > i will get output as o to n-1
# in loc function suppose my range is 0 to n > i will get output as 0 to n
#loc function if you want to access columns you have to use column names

In [ ]:
df.loc[:,"Name"]

In [ ]:
df.loc[:,["Name", "Marks"]]

In [ ]:
df.loc[5:8, ["Name","Age", "City"]]

In [45]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [ ]:
# task1 : select Name Colum (loc, iloc, normal)
print(df["Name"])
print(df.loc[:,"Name"])
print(df.iloc[:,1])
# taks2: select Name, City Columns (loc, iloc, normal)
print(df[["Name", "City"]])
print(df.loc[:,["Name", "City"]])
print(df.iloc[:,[1,3]])
#task3: select first 3 rows(loc, iloc)
print(df.loc[0:2])
print(df.iloc[0:3])
# taks4: select first 3 rows and first 2 columns(loc, iloc)
print(df.loc[0:1,["Student_ID","Name"]])
print(df.iloc[0:2,0:2])
#task5 : select all rows and marks columns (loc, iloc)
print(df.loc[:,"Marks"])
print(df.iloc[:,4])

In [ ]:
df

In [ ]:
df[df["Marks"]>80]

In [ ]:
# filter marks greater than 80
df[df["Marks"]>80]

In [ ]:
#marks less than 90
df[df["Marks"]<=90]

In [ ]:
df[df["Age"]>=21]

In [ ]:
df[df["City"] == "Vijayawada"]

In [ ]:
df[(df["Marks"]>80) & (df["Age"]>=21)]

In [ ]:
df[(df["Marks"]>80)  | (df["Age"]>=21)]

In [ ]:
df.loc[df["Marks"]>80 , ["Name" ,"Marks"]]

In [ ]:
#task1 filter students marks with less than 70
#taks2 filter stusents from banglore
#task3 students age less than 30
#task4 students with marks greater than 25 or age greater than 30
#taks5 show only name and age where city is chennai

In [73]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [77]:
# iloc()
# #rows, columns index values 0:3 =>0,1,2
# df.iloc[0:3] =>0,1,2
df.iloc[0:3,0:3]
# loc 0:3 => 0,1,2,3 =>0:2 =>0,1,2

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [78]:
df.loc[0:2,["Student_ID","Name", "Age"]]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [ ]:
#task1 filter students marks with less than 70
#taks2 filter stusents from banglore
#task3 students age less than 30
#task4 students with marks greater than 25 or age greater than 30
#taks5 show only name and age where city is chennai

In [79]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [ ]:
#task1 filter students marks with less than 90
df[df["Marks"]<90]

In [ ]:
#taks2 filter stusents from banglore
df[df["City"] == "Bangalore"]

In [ ]:
#task3 students age less than 30
df[df["Age"]<30]

In [ ]:
#task4 students with marks greater than 25 or age greater than 30
df[(df["Marks"]>25)|(df["Age"]<30)]

In [86]:
#taks5 show only name and age where city is chennai
df.loc[df["City"]=="Chennai" , ["Name", "Age"]]

   Name  Age
2  Sita   21

In [ ]:
#sorting :arranging data in a particular order
#usually ascending order, descending order
#df.sort_values(by="column name")

In [ ]:
df

In [ ]:
df.sort_values(by="Marks") #ascending order

In [ ]:
df.sort_values(by="Marks", ascending=False) #descending order

In [ ]:
df.sort_values(by="City")

In [ ]:
df.sort_values(by=["City", "Marks"])