<a href="https://colab.research.google.com/github/Santhoshkumar5655/datasciencelearning/blob/main/string_processing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
# # string processing in pandas means perfroming operations on text(string)
# # data stored in dataframe columns using pandas string functions
# cHevuri
# 1000,
# 50
# chevurisanthosh@gmail.com
# chevurisantosh@outlook.com
# "    santosh"

In [69]:
s = "   lahari"
#if we want to remove spaces we will use strip method
#lstrip it will remove spaces in left side
#rstrip it will remove spaces in right side only
#strip #it will remove spaces from both sides
print(s.strip())

lahari

In [70]:
import pandas as pd

In [71]:
df = pd.read_csv("/content/drive/MyDrive/datsetsfordatasciencebytexl/string_processing_dataset.csv")

In [72]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,RAJU@YAHOO.COM,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [73]:
df["email"] = df["email"].str.lower() #we are converting into the lower case
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,Vijayawada,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,vizag,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,Guntur,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [74]:
#convert cities into uppercase
df["city"] = df["city"].str.upper()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,RAJU KUMAR,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,kiran reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,SURESH BABU,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [75]:
#converting customer_name column into title
df["customer_name"] = df["customer_name"].str.title()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024

In [76]:
df["name_length"] = df["customer_name"].str.len()
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,16
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,11
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,11
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,12

In [77]:
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,Rs 1000,9876543210,PRD-101,12-Jan-2024,16
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"Rs 3,500",9988776655,PRD-303,18-Mar-2024,11
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,11
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,Rs 750,9012345678,PRD-505,30-May-2024,12

In [61]:
# regex = false tella pandas to treat the value as normal text and not as a special pattern

In [78]:
df["purchase_amount"] = df["purchase_amount"].str.replace("Rs ", "", regex= False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,16
1,Raju Kumar,raju@yahoo.com,HYDERABAD,$250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"3,500",9988776655,PRD-303,18-Mar-2024,11
3,Suresh Babu,suresh@outlook.com,GUNTUR,"$1,200",9871234567,PRD-404,22-Apr-2024,11
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [79]:
df["purchase_amount"] = df["purchase_amount"].str.replace("$", "", regex= False)
df

,customer_name,email,city,purchase_amount,phone,product_code,join_date,name_length
0,Santhosh Chevuri,santhosh@gmail.com,VIJAYAWADA,1000,9876543210,PRD-101,12-Jan-2024,16
1,Raju Kumar,raju@yahoo.com,HYDERABAD,250,9123456789,PRD-202,05-Feb-2024,10
2,Kiran Reddy,kiran@gmail.com,VIZAG,"3,500",9988776655,PRD-303,18-Mar-2024,11
3,Suresh Babu,suresh@outlook.com,GUNTUR,"1,200",9871234567,PRD-404,22-Apr-2024,11
4,Lakshmi Devi,lakshmi@gmail.com,TIRUPATI,750,9012345678,PRD-505,30-May-2024,12

In [ ]:
df["purchase_amount"] = df["purchase_amount"].str.replace(",", "", regex= False)
df

In [ ]:
df["is_mail"] = df["email"].str.contains("gmail")
df

In [ ]:
df["startswithv"] = df["city"].str.startswith("V")
df

In [ ]:
df["email_parts"] = df["email"].str.split("@").str[0]
df

In [ ]:
df["email_parts_combined"] = df["email"].str.split("@")
df
# chevurisanthosh@gmail.com = [chevurisanthosh, gmail.com]

In [ ]:
df["city_code"] = df["city"].str[:3]
df

In [ ]:
df["is_numeric"] = df["phone"].astype(str).str.isnumeric()
df

In [ ]:
df["product_code"] = df["product_code"].str.removeprefix("PRD-")
df